services:
  web:
    build: .
    command: gunicorn ea1rkv.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - static_data:/app/staticfiles
      - media_data:/app/media
    expose:
      - "8000"
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=ea1rkv.settings.production
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  db:
    image: postgres:16-alpine
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_data:/app/staticfiles
      - media_data:/app/media
    depends_on:
      - web

volumes:
  postgres_data:
  static_data:
  media_data:
  redis_data:

networks:
  quendaward-network:
    driver: bridge
