# Generated by Django 5.2.10 on 2026-02-02 17:40

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="about_description",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="We are a community of amateur radio operators dedicated to advancing the art, science, and practice of radio communication. Whether you are a seasoned ham or just getting started, you are welcome here.",
                help_text="Description of the radio club.",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="about_title",
            field=models.CharField(
                blank=True, default="About Our Club", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="activities_title",
            field=models.CharField(
                blank=True, default="Our Activities", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="activity_1_description",
            field=models.TextField(
                blank=True,
                default="Regular on-air activity across HF and VHF bands, including nets, ragchewing, and DX contacts around the world.",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="activity_1_title",
            field=models.CharField(
                blank=True, default="HF & VHF Operating", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="activity_2_description",
            field=models.TextField(
                blank=True,
                default="We participate in major contests and ARRL Field Day, setting up portable stations and operating around the clock.",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="activity_2_title",
            field=models.CharField(
                blank=True, default="Contests & Field Day", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="activity_3_description",
            field=models.TextField(
                blank=True,
                default="We offer study sessions and exam preparation for Technician, General, and Amateur Extra license classes.",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="activity_3_title",
            field=models.CharField(
                blank=True, default="Training & Licensing", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="activity_4_description",
            field=models.TextField(
                blank=True,
                default="Our members train in emergency communications and support local agencies through ARES and RACES programs.",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="activity_4_title",
            field=models.CharField(
                blank=True, default="Emergency Communications", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="banner_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional hero/banner image.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="banner_subtitle",
            field=models.CharField(
                blank=True,
                default="Connecting amateur radio enthusiasts since day one",
                help_text="Subtitle displayed below the main heading.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="banner_title",
            field=models.CharField(
                blank=True,
                default="Welcome to the Radio Club",
                help_text="Main heading displayed in the hero section.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="club_callsign",
            field=models.CharField(
                blank=True,
                help_text="The club's amateur radio callsign (e.g. W1AW).",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="contact_description",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="Interested in joining or have questions? Reach out to us and we will be happy to help you get started in amateur radio.",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="contact_email",
            field=models.EmailField(
                blank=True, default="info@radioclub.example.com", max_length=254
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="contact_title",
            field=models.CharField(blank=True, default="Get In Touch", max_length=255),
        ),
        migrations.AddField(
            model_name="homepage",
            name="meeting_description",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="We meet on the first Thursday of each month at 7:00 PM. All meetings are open to the public — bring a friend!",
                help_text="Information about club meetings and events.",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="meeting_title",
            field=models.CharField(
                blank=True, default="Meetings & Events", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="repeater_info",
            field=models.CharField(
                blank=True,
                help_text="Club repeater frequency and details (e.g. 146.940 MHz, -600 kHz offset, PL 100.0).",
                max_length=255,
            ),
        ),
    ]
