# Generated by Django 5.2.11 on 2026-02-07 19:29

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="RadioIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("introduction", wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                "verbose_name": "Sección Radio",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="RadioPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="bi-broadcast",
                        help_text="Clase de icono Bootstrap Icons (e.g., bi-broadcast, bi-globe, bi-cloud-sun)",
                        max_length=50,
                    ),
                ),
                ("introduction", models.TextField(blank=True, max_length=500)),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("heading", 2),
                            ("paragraph", 3),
                            ("image", 7),
                            ("callout", 10),
                            ("button", 16),
                            ("cards", 23),
                            ("embed", 24),
                            ("table", 25),
                            ("raw_html", 26),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("h2", "H2"),
                                        ("h3", "H3"),
                                        ("h4", "H4"),
                                    ],
                                    "help_text": "Nivel del encabezado",
                                },
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Texto del encabezado", "required": True},
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("heading_level", 0), ("text", 1)]],
                                {},
                            ),
                            3: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "bold",
                                        "italic",
                                        "ol",
                                        "ul",
                                        "hr",
                                        "link",
                                        "document-link",
                                        "image",
                                        "embed",
                                        "h2",
                                        "h3",
                                        "h4",
                                        "blockquote",
                                    ],
                                    "icon": "pilcrow",
                                    "label": "Párrafo",
                                },
                            ),
                            4: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"required": True},
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Pie de imagen", "required": False},
                            ),
                            6: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Atribución de la imagen",
                                    "required": False,
                                },
                            ),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 4), ("caption", 5), ("attribution", 6)]],
                                {},
                            ),
                            8: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["bold", "italic", "link"],
                                    "help_text": "Texto del aviso",
                                },
                            ),
                            9: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("info", "Información (azul)"),
                                        ("success", "Éxito (verde)"),
                                        ("warning", "Advertencia (amarillo)"),
                                        ("danger", "Peligro (rojo)"),
                                    ],
                                    "help_text": "Color de fondo del aviso",
                                },
                            ),
                            10: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 8), ("background_color", 9)]],
                                {},
                            ),
                            11: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Texto del botón", "required": True},
                            ),
                            12: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {
                                    "help_text": "URL externa (opcional)",
                                    "required": False,
                                },
                            ),
                            13: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "help_text": "Página interna (opcional)",
                                    "required": False,
                                },
                            ),
                            14: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "help_text": "Abrir en nueva pestaña",
                                    "required": False,
                                },
                            ),
                            15: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("primary", "Primario"),
                                        ("secondary", "Secundario"),
                                        ("outline", "Contorno"),
                                    ],
                                    "help_text": "Estilo del botón",
                                },
                            ),
                            16: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("text", 11),
                                        ("url", 12),
                                        ("page", 13),
                                        ("open_in_new_tab", 14),
                                        ("style", 15),
                                    ]
                                ],
                                {},
                            ),
                            17: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"required": False},
                            ),
                            18: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Título de la tarjeta", "required": True},
                            ),
                            19: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["bold", "italic", "link"],
                                    "help_text": "Contenido de la tarjeta",
                                },
                            ),
                            20: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Texto del enlace", "required": True},
                            ),
                            21: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("text", 20),
                                        ("url", 12),
                                        ("page", 13),
                                        ("open_in_new_tab", 14),
                                    ]
                                ],
                                {"required": False},
                            ),
                            22: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("image", 17),
                                        ("title", 18),
                                        ("text", 19),
                                        ("link", 21),
                                    ]
                                ],
                                {},
                            ),
                            23: (
                                "wagtail.blocks.ListBlock",
                                (22,),
                                {"icon": "list-ul", "label": "Tarjetas"},
                            ),
                            24: (
                                "wagtail.embeds.blocks.EmbedBlock",
                                (),
                                {
                                    "help_text": "Inserta una URL de YouTube, Vimeo, etc.",
                                    "icon": "media",
                                    "label": "Contenido embebido",
                                },
                            ),
                            25: (
                                "wagtail.contrib.table_block.blocks.TableBlock",
                                (),
                                {
                                    "label": "Tabla",
                                    "template": "core/blocks/table_block.html",
                                },
                            ),
                            26: (
                                "wagtail.blocks.RawHTMLBlock",
                                (),
                                {
                                    "help_text": "Usa con precaución. No se valida el contenido HTML.",
                                    "icon": "code",
                                    "label": "HTML sin procesar",
                                },
                            ),
                        },
                    ),
                ),
                (
                    "header_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Página técnica de radio",
            },
            bases=("wagtailcore.page",),
        ),
    ]
