# Generated by Django 5.1.15 on 2026-03-20 17:33

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(
                        default="EA1RKV", max_length=255, verbose_name="Hero title"
                    ),
                ),
                (
                    "hero_subtitle",
                    models.CharField(
                        default="Unión de Radioaficionados de Vigo-Val Miñor",
                        max_length=255,
                        verbose_name="Hero subtitle",
                    ),
                ),
                (
                    "hero_cta_text",
                    models.CharField(
                        blank=True,
                        default="Ver Blog",
                        max_length=50,
                        verbose_name="Call to action text",
                    ),
                ),
                (
                    "hero_cta_link",
                    models.CharField(
                        blank=True,
                        help_text="Relative URL, e.g. /blog/",
                        max_length=255,
                        verbose_name="Call to action link",
                    ),
                ),
                (
                    "club_description",
                    wagtail.fields.RichTextField(
                        blank=True, verbose_name="Club description"
                    ),
                ),
                (
                    "club_callsign",
                    models.CharField(
                        default="EA1RKV", max_length=20, verbose_name="Club callsign"
                    ),
                ),
                (
                    "club_frequency",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 145.550 MHz",
                        max_length=50,
                        verbose_name="Club frequency",
                    ),
                ),
                (
                    "club_locator",
                    models.CharField(
                        blank=True,
                        help_text="e.g. IN52JD",
                        max_length=20,
                        verbose_name="QTH Locator",
                    ),
                ),
            ],
            options={
                "verbose_name": "Home Page",
            },
            bases=("wagtailcore.page",),
        ),
    ]
