# Generated by Django 5.1.15 on 2026-03-27 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="club_callsign",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="club_description",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="club_frequency",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="club_locator",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="hero_cta_link",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="hero_cta_text",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="hero_subtitle",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="hero_title",
        ),
        migrations.AddField(
            model_name="homepage",
            name="banner_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Imagen panorámica que aparece debajo de la cabecera",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Imagen de cabecera",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="banner_subtitle",
            field=models.CharField(
                blank=True,
                default="Unión de Radioaficionados de Vigo-Val Miñor",
                max_length=255,
                verbose_name="Subtítulo del banner",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="banner_title",
            field=models.CharField(
                default="EA1RKV", max_length=255, verbose_name="Título del banner"
            ),
        ),
    ]
